"
I represent a Fung ""cell"" in 3D grid space.

My instances are constructed with the `location:` or `x:y:z:` messages.

My messages deal with bounds and locations in 3D grid space.

Reference:
Fung YC. A model of the lung structure and its validation. J Appl Physiol (1985). 1988;64(5):2132-2141. doi:10.1152/jappl.1988.64.5.2132

"
Class {
	#name : 'FungVoxel',
	#superclass : 'Voxel',
	#category : 'Lungsim',
	#package : 'Lungsim'
}
